# Generated by Django 3.1.6 on 2021-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210219_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancedata',
            name='data',
            field=models.TextField(max_length=1000000),
        ),
    ]
